name: My Workflow
on:
  push:
  workflow_dispatch:
  pull_request:
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        with:
          branch: gh-pages
          folder: .vuepress/dist/
          clean-exclude: site/
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: /site/.
          dst_path: /site/
          src_branch: main
          dst_branch: gh-pages
          dst_owner: 2asa
          dst_repo_name: 2asa.github.io
          clean: true
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
  copy:
    name: Copy docs folder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
