name: Copy
on:
  push:
  workflow_dispatch:
  pull_request:
jobs:
  copy:
    name: copy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Copy
        uses: andstor/copycat-action@v3
        with:
    personal_token: ${{ secrets.ACCESS_TOKEN }}
    src_path: /docs/
    src_branch: main
    dst_branch: gh-pages
    dst_owner: 2asa
    dst_repo_name: copycat-action
    clean: true